name: Vite Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      http_proxy: http://localhost:7890
      https_proxy: http://localhost:7890

    steps:
      - name: Pull Latest Code
        run: |
          cd /home/chtne/zzszwiki
          git pull origin main

      - name: Install Node.js Dependencies
        run: pnpm install
        working-directory: /home/chtne/zzszwiki

      - name: Run Lint Check
        run: pnpm run lint
        working-directory: /home/chtne/zzszwiki

      - name: Build Vite Project
        run: pnpm run build
        working-directory: /home/chtne/zzszwiki

      - name: Reload Nginx
        run: sudo systemctl reload nginx
        working-directory: /home/chtne/zzszwiki